[project]
name = "sid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sphinx>=9.1.0",
    "sphinx-markdown-builder>=0.6.9",
    "sphinx-simplepdf>=1.7.0",
]
